### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by RohitVermaOP** [JonForShort/android-tools#15]
Can you add .so file? For aidl and aapt2

**Comment by RohitVermaOP** [comment]
How compile these librarys using termux?

**Comment by RohitVermaOP** [comment]
Please compile this. 
https://github.com/RohitVermaOP/aapt2

**Comment by JonForShort** [comment]
Hi @RohitVermaOP , you can find the aap2 executable for armeabi-v7a at the following locations.

https://github.com/JonForShort/android-tools/blob/master/build/android-9.0.0_r33/aapt2/armeabi-v7a/bin/aapt2
https://github.com/JonForShort/android-tools/blob/master/build/android-9.0.0_r33/aapt2/armeabi-v7a/lib/libaapt2.so

Hope this works for you.

**Comment by RohitVermaOP** [comment]
aapt.so not working
![Uploading Screenshot_2021-03-15-15-02-35-24_d55cbd1e27f922836510f4a3bfe3bff1.jpg…]()

**Comment by JonForShort** [comment]
Hi @RohitVermaOP , this might be an incompatibility with the platform you are running on.  What version of Android is your device?   Is it greater than Android 9+?

**Comment by RohitVermaOP** [comment]
Android 10

**Comment by RohitVermaOP** [comment]
> Please compile this.
> https://github.com/RohitVermaOP/aapt2

Please

**Comment by RohitVermaOP** [comment]
Because bin not executing on Android 9+

**Comment by JonForShort** [comment]
Thanks @RohitVermaOP , can you double check that you are using the right ABI architecture for your device? If you are running an emulator, you will need to be sure to use the ```x86``` binaries.

https://github.com/JonForShort/android-tools/tree/master/build/android-9.0.0_r33/aapt2/x86/lib

If you are running this on a physical device, then you need to use the ARM ones.

https://github.com/JonForShort/android-tools/tree/master/build/android-9.0.0_r33/aapt2/arm64-v8a/lib64
