### ISSUE TITLE
AAPT2 in armv7l (32 bit)

### ISSUE THREAD

**Issue by MarkDroid** [JonForShort/android-tools#16]
hi, i find you work useful, what about adding a aapt2 to this repository because i need it to work in armv7l ( a 32-bit processor ) for android. please reply a soon as possible and sorry for my broken english.

**Comment by JonForShort** [comment]
Hi @MarkDroid , you should be able to use this binary here.

https://github.com/JonForShort/android-tools/blob/master/build/android-9.0.0_r33/aapt2/armeabi-v7a/bin/aapt2

Please give this a try and tell me if you run into any issues.

**Comment by MarkDroid** [comment]
Thanks @JonForShort, i have tested the aapt2 that you give and it's working well on android, thank you very much and i hope you update the android built tools to the latest version ( android-11 ). keep it up the amazing work ♥️
