### ISSUE TITLE
aapt2.so not working

### ISSUE THREAD

**Issue by RohitVermaOP** [JonForShort/android-tools#17]
aapt2.so not working
![Screenshot_2021-03-15-15-08-22-62_d55cbd1e27f922836510f4a3bfe3bff1](https://user-images.githubusercontent.com/56387351/111133304-62931500-85a0-11eb-8f24-f16e3490f77a.jpg)

_Originally posted by @RohitVermaOP in https://github.com/JonForShort/android-tools/issues/15#issuecomment-799267772_

**Comment by JonForShort** [comment]
Hi @RohitVermaOP , can you try using the android-11 build and see if it works?

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt2/arm64-v8a/lib64/libaapt2.so
