### ISSUE TITLE
Update Tools

### ISSUE THREAD

**Issue by MarkDroid** [JonForShort/android-tools#18]
Hi again, can you update aapt and aapt2 for the last version please ? ( android-11) since me and my team interested in this repo because it's helpful to integrate android tools in apk files . . .

**Comment by MarkDroid** [comment]
sir please can you reply

**Comment by JonForShort** [comment]
Hi @MarkDroid , sure I have been meaning to update all the tools for android 11.  I'll try to get to this in a bit.

**Comment by MarkDroid** [comment]
very glad to hear that
