### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by SectionTN** [JonForShort/android-tools#19]
bro, we are still waiting for the new android-11 AAPT2 and more, can you upload them ?

**Comment by AlucardTN** [comment]
....

**Comment by JonForShort** [comment]
Hi @AlucardTN , apologies for the delay.  I have been really busy.  I'll try to get the new binaries this week.

**Comment by AlucardTN** [comment]
yooo good news for weeks, thanks!

**Comment by JonForShort** [comment]
Hi @AlucardTN , were you interested in primarily aapt and aap2? If so, I can get started on those first.

**Comment by AlucardTN** [comment]
hello, I'm interested in aapt2

**Comment by AlucardTN** [comment]
those binaries that you make help us a lot to create a small IDE in android, you can for example check out aide, sketchware ( you can get them from play store ).

**Comment by JonForShort** [comment]
@AlucardTN ,  seems like a really cool project :+1: It's this one right? https://docs.sketchware.io/

**Comment by AlucardTN** [comment]
yes that's project, not mine, but me and a team modding it ( reverse engineering the apk ) etc... I'm very excited for the aapt2 😍

**Comment by AlucardTN** [comment]
@JonForShort is it done or not yet ?

**Comment by JonForShort** [comment]
Hi @AlucardTN , I just uploaded them now.

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt2

I tested it on my test phone and it seems to work fine.  Please let me know if you have issues with them.

**Comment by AlucardTN** [comment]
yoo, thank you, im gonna test it right now, can you then start on zipalign and aapt2, this will be very enough, thank you again

**Comment by JonForShort** [comment]
You can find zipalign here as well.

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/zipalign

**Comment by AlucardTN** [comment]
thanks, only still the normal aapt, good luck bro on it

**Comment by AlucardTN** [comment]
@JonForShort, i have tested it now, everything goes fine like compilation, .flat generation etc...

**Comment by AlucardTN** [comment]
one more question, is android 12 source is available now ?

**Comment by JonForShort** [comment]
I just checked and there doesn't seem to be an official branch for it yet.  The android 12 source code is still in the 'master' branch.  The latest released branch is 'android-11.0.0_r35'.

**Comment by AlucardTN** [comment]
that's okay, don't forget to build an aapt2 when android 12 source code is available 😆 and thanks

**Comment by AlucardTN** [comment]
hello again, how much android-11 aapt took to complete it.

**Comment by AlucardTN** [comment]
take your time, please inform me when it's ready and thanks

**Comment by JonForShort** [comment]
Hi @AlucardTN , I was able to figure out the crash issue.  I posted the binaries for ```aapt```. 

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt

I tested them on my android 11 phone and they seem to work fine.  Please tell me if you have any issues.

**Comment by SectionTN** [comment]
yeeeey !!!, thanks bro, and keep the good work up !, we really need those binaries thanks again.

**Comment by JonForShort** [comment]
Sure no problem :+1:

**Comment by SectionTN** [comment]
![Screenshot_20210506-053122.png](https://user-images.githubusercontent.com/73752904/117242064-c9aca780-ae34-11eb-8f96-269f66168738.png)

@JonForShort i have encountered this problem with AAPT of android-11

**Comment by JonForShort** [comment]
Thanks @AlucardTN  for reporting this. What device are you testing on?

**Comment by SectionTN** [comment]
sorry for that late, i was testing on motorola e4 android 7.1

**Comment by SectionTN** [comment]
no reply untill now
