### ISSUE TITLE
please Adding android-11 binaries for aapt

### ISSUE THREAD

**Issue by shuajinanhai** [JonForShort/android-tools#21]
please build aapt and aapt2,  thank you!!!

**Comment by JonForShort** [comment]
Hi @shuajinanhai , you can find the binaries for this here.

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt
https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt2

**Comment by RohitVermaOP** [comment]
android-11 binaries for Android version 11?

**Comment by rupeshkumar22** [comment]
Hey, @JonForShort  I wanted to know if the android-11.0.0_r33 compatible to run on the lower APIs i.e android 10,9,8,7 etc.
The same I wanted to know for android-9.0.0 tools that you have provided. I am using these bin/binaries through `Runtime.getRuntime().exec()` in an android project and I wanted to run at least one binary of aapt and aapt2 for all the platforms devices. Not sure which binary to use on which platform and architecture. Can you explain more about it?

**Comment by timscriptov** [comment]
@rupesh-kumar-lpu I checked. Binaries work on older devices!

**Comment by JonForShort** [comment]
Closing issue as this seems to be resolved.  @shuajinanhai , please let me know if you have any issues with the binaries.

@rupesh-kumar-lpu, regarding your question below.

> Hey, @JonForShort I wanted to know if the android-11.0.0_r33 compatible to run on the lower APIs i.e android 10,9,8,7 etc.
> The same I wanted to know for android-9.0.0 tools that you have provided. I am using these bin/binaries through `Runtime.getRuntime().exec()` in an android project and I wanted to run at least one binary of aapt and aapt2 for all the platforms devices. Not sure which binary to use on which platform and architecture. Can you explain more about it?

Good question.  I haven't really tested this enough to know which binaries should work for which platforms. If someone has the time to test this, I can create a wiki page and put the results in it.  Unfortunately, I don't have much time to do this myself.  Sorry about that!
