### ISSUE TITLE
aidl

### ISSUE THREAD

**Issue by ashish0304** [JonForShort/android-tools#3]
Please build aidl.
Thanks.

**Comment by thejunkjon** [comment]
Hi @ashish0304 , can you provide a link to the AIDL you would like me to add?  I can put this in the *wish list* and try to get to it.

**Comment by JonForShort** [comment]
I have added _aidl_ for android 11 platform.  

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aidl

Please give this a try and let me know if it doesn't work for you.  Thanks!
